// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    projecte_bc
    (
        init => init
        claim_attendance => claim_attendance
        deposit => deposit
        getAttendanceStatus => get_attendance_status
        getEgldTransactions => get_egld_transactions
        getTotalClasses => total_classes
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
